const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const RentalMarket = await hre.ethers.getContractFactory("RentalMarket");
  const market = await RentalMarket.deploy();
  await market.waitForDeployment();

  const address = await market.getAddress();
  console.log("RentalMarket deployed to:", address);

  // Drop the address + ABI into the frontend so app.js can load it.
  const artifact = await hre.artifacts.readArtifact("RentalMarket");
  const out = `// Auto-generated by scripts/deploy.js — do not edit by hand.
window.CONTRACT_INFO = ${JSON.stringify({ address, abi: artifact.abi }, null, 2)};
`;
  const outPath = path.join(__dirname, "..", "frontend", "contract-info.js");
  fs.writeFileSync(outPath, out);
  console.log("Wrote", outPath);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
